---
namespace: ibm
name: qradar
authors:
  - Ansible Security Team (https://github.com/ansible-security)
dependencies:
  ansible.netcommon: ">=2.5.1"
description: Ansible Security Collection for IBM Qradar SIEM
license_file: LICENSE
tags:
  - security
  - qradar
repository: https://github.com/ansible-collections/ibm.qradar
documentation: https://github.com/ansible-collections/ibm.qradar
homepage: https://github.com/ansible-collections/ibm.qradar
issues: https://github.com/ansible-collections/ibm.qradar/issues
readme: README.md
version: 2.1.1-devel
